kind: pipeline
type: docker
name: build

workspace:
  base: /drone/src
  path: your-repo-name

steps:
  - name: build
    image: golang:1.22-alpine
    commands:
      - apk add --no-cache git
      - go mod tidy
      - go build -v -o myapp ./...
      - ls -lh myapp

  - name: test
    image: golang:1.22-alpine
    commands:
      - ls -lh
      - ./myapp --version
      - go test ./... -v

  - name: archive
    image: alpine
    commands:
      - apk add --no-cache zip
      - ls -la  # Kiểm tra file myapp có trong workspace không
      - zip myapp-${DRONE_BUILD_NUMBER}.zip myapp
      - ls -lh *.zip
      - pwd  # Sẽ hiển thị /drone/src/your-repo-name
