kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: golang:1.22.12-alpine3.20
    pull: if-not-exists   # chỉ pull nếu chưa có
    commands:
      - go version
      - go mod tidy
      - go build -v ./...

  - name: test
    image: golang:1.22-alpine
    pull: if-not-exists
    commands:
      - go test ./... -v
