kind: pipeline
type: docker
name: build

clone:
  disable: false

workspace:
  base: /drone/src
  path: .

steps:
  - name: build
    image: golang:1.22-alpine
    pull: if-not-exists
    commands:
      - apk add --no-cache git bash
      - go version
      - go mod tidy
      - go build -v -o myapp ./...
      - ls -lh myapp
    volumes:
      - name: artifacts
        path: /drone/src/artifacts

  - name: test
    image: golang:1.22-alpine
    pull: if-not-exists
    commands:
      - ls -lh /drone/src
      - ./myapp --version
      - go test ./... -v
    volumes:
      - name: artifacts
        path: /drone/src/artifacts

volumes:
  - name: artifacts
    host:
      path: /tmp/drone-artifacts
