kind: pipeline
type: docker
name: build

volumes:
  - name: current-dir
    host:
      path: /tmp/drone-artifacts  # Hoặc đường dẫn tuyệt đối đến thư mục bạn muốn

workspace:
  base: /drone/src
  path: .

steps:
  - name: build
    image: golang:1.22-alpine
    commands:
      - apk add --no-cache git
      - go mod tidy
      - go build -v -o myapp ./...
      - ls -lh myapp

  - name: test
    image: golang:1.22-alpine
    commands:
      - ./myapp --version
      - go test ./... -v

  - name: archive
    image: alpine
    volumes:
      - name: current-dir
        path: /artifacts
    commands:
      - apk add --no-cache zip
      - cp myapp /artifacts/
      - cd /artifacts && zip myapp-${DRONE_BUILD_NUMBER}.zip myapp
      - echo "✅ File zip đã được lưu tại: /tmp/drone-artifacts/myapp-${DRONE_BUILD_NUMBER}.zip"
      - ls -lh /artifacts/*.zip
