kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: golang:1.22-alpine
    commands:
      - apk add --no-cache git bash zip
      - go mod tidy
      - go build -v -o myapp ./...
      - ls -lh myapp

  - name: test
    image: golang:1.22-alpine
    commands:
      - ./myapp --version
      - go test ./... -v

  - name: archive
    image: alpine
    commands:
      - apk add --no-cache zip
      - zip myapp-${DRONE_BUILD_NUMBER}.zip myapp
      - cp myapp-${DRONE_BUILD_NUMBER}.zip /cache/  # COPY FILE VÀO CACHE
      - echo "File đã được lưu vào cache:"
      - ls -lh /cache/*.zip
    volumes:
      - name: cache
        path: /cache

  - name: store-artifact
    image: alpine
    commands:
      - echo "Các file trong cache volume:"
      - ls -lh /cache/
      - echo "File .zip có sẵn tại: /cache/myapp-${DRONE_BUILD_NUMBER}.zip"
      - cp /cache/myapp-${DRONE_BUILD_NUMBER}.zip ./
      - echo "File đã được copy về workspace hiện tại"
      - ls -lh *.zip
    volumes:
      - name: cache
        path: /cache
