kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: golang:1.22-alpine
    commands:
      - apk add --no-cache git bash zip
      - go mod tidy
      - go build -v -o myapp ./...
      - ls -lh myapp

  - name: test
    image: golang:1.22-alpine
    commands:
      - ./myapp --version
      - go test ./... -v

  - name: archive
    image: alpine
    commands:
      - apk add --no-cache zip
      - zip myapp-${DRONE_BUILD_NUMBER}.zip myapp
      - ls -lh *.zip

  - name: use-artifact
    image: alpine
    commands:
      - echo "File .zip có sẵn trong workspace:"
      - ls -lh *.zip
      - echo "Tên file: myapp-${DRONE_BUILD_NUMBER}.zip"
